export const answers = [
  "warum ist die Banane krumm? Weil niemand in den Urwald zog und die Banane gerade bog.",
  "ich bin heute so verwirrt, ich habe sogar im Internet nachgeschaut, wo meine Brille ist.",
  "ich habe versucht, vegetarisch zu leben... Aber es war ein Steak.",
  "warum gehen Geister nie zum Arzt? Weil sie sich nur einbilden, krank zu sein.",
  "ich habe einen neuen Frisbee gekauft. Er ist umwerfend!",
  "warum können Seeräuber keine Kreise zeichnen? Weil sie Pi-raten.",
  "ich wollte einen Witz über Zeitreisen machen, aber ihr fandet ihn nicht lustig.",
  "was sagt ein Null zu einer Acht? Schicker Gürtel!",
  "ich habe einen Job in einer Bäckerei bekommen, weil ich Kuchen mag. Es ist eine Tortur.",
  "warum sind Elektriker nie unglücklich? Weil sie den richtigen Draht zu positiver Energie haben.",
  "ich habe versucht, Schokolade zu hassen, aber es ist keine leichte Feindtätigkeit.",
  "warum können Elefanten nicht fliegen? Weil sie zu schwerfällig sind.",
  "ich habe einen Witz über ein Dach gemacht. Der ist über euren Köpfen.",
  "warum sind Computer so klug? Weil sie ihre Informationen aus erster Hand bekommen.",
  "ich wollte einen Diät-Witz machen, aber ich habe keinen guten gefunden. Sie sind alle zu fett.",
  "warum gehen Fische nie zur Schule? Weil sie Schwarmintelligenz haben.",
  "ich habe einen Witz über einen Aufzug gemacht. Er war auf mehreren Ebenen lustig.",
  "warum ist der Computer kalt? Weil er Windows offen hat.",
  "ich wollte einen Witz über Unendlichkeit machen, aber er hatte kein Ende.",
  "warum sind Bücher immer so cool? Weil sie viele Fans haben.",
  "ich habe einen Witz über Stille gemacht, aber niemand hat ihn gehört.",
  "warum sind Zitronen sauer? Weil sie das Leben nicht süß finden.",
  "ich wollte einen Witz über den Weltraum machen, aber er war zu weit draußen.",
  "warum sind Mathematikbücher traurig? Weil sie zu viele Probleme haben.",
  "ich habe einen Witz über Wasser gemacht, aber er ist durchgeflossen.",
  "warum sind Spinnen gute Webentwickler? Weil sie großartige Netze bauen.",
  "ich wollte einen Witz über Pizza machen, aber er war zu käsig.",
  "warum ist der Sand am Strand immer nass? Weil das Meer ihn wellt.",
  "ich habe einen Witz über einen Tunnel gemacht, aber er sah kein Licht.",
  "warum sind Berge nicht kalt? Weil sie eine Schneedecke haben.",
  "ich wollte einen Witz über den Vollmond machen, aber er war nicht ganz rund.",
  "warum sind Buchhalter immer so ruhig? Weil sie gute Zahlen haben.",
  "ich habe einen Witz über einen Stift gemacht, aber er war nicht spitz.",
  "warum ist der Tee so alt? Weil er in den Beuteln geblieben ist.",
  "ich wollte einen Witz über einen Kalender machen, aber seine Tage sind gezählt.",
  "warum sind Zwerge so gute Arbeiter? Weil sie sich nicht lang machen.",
  "ich habe einen Witz über einen Frosch gemacht, aber er sprang nicht.",
  "warum ist der Computer so schlau? Weil er einen Chip hat.",
  "ich wollte einen Witz über die Sonne machen, aber er strahlte zu sehr.",
  "warum sind Vögel immer nach dem Regen da? Weil es dann Wurmfestspiele gibt.",
  "ich habe einen Witz über einen Baum gemacht, aber er blätterte um.",
  "warum ist der Kaffee so aufgeregt? Weil er aufgebrüht wurde.",
  "ich wollte einen Witz über einen Fußball machen, aber er ging ins Aus.",
  "warum sind Katzen so gute Musiker? Weil sie mit den Pfoten klavier spielen.",
  "ich habe einen Witz über einen Fisch gemacht, aber er schwamm davon.",
  "warum ist der Himmel so fröhlich? Weil er blau macht.",
  "ich wollte einen Witz über einen Stuhl machen, aber er saß nicht gut.",
  "warum sind Kerzen so romantisch? Weil sie beim Abendessen leuchten.",
  "ich habe einen Witz über einen Hammer gemacht, aber er schlug fehl.",
  "warum sind Züge so pünktlich? Weil sie auf Schienen laufen."
];